name: request_builder
description: Easy to make http/https requests for RESTful 
version: 1.0.5+8

environment:
  sdk: ^3.0.5

dependencies:
  meta: ^1.12.0
  http: ^1.2.1
  json_path: ^0.7.1
  logging: ^1.2.0

dev_dependencies:
  benchmark_harness: ^2.2.2
  lints: ^3.0.0
  test: ^1.21.0
